### ISSUE TITLE
Expo google maps is not working

### ISSUE THREAD

**Issue by rudsonramon** [calebnance/expo-uber#12]
Hi there, I tried to use the project but the map is not loading, can you help me?

**Comment by calebnance** [comment]
Hey, make sure you are allowing expo to use location (select permission, at least "while using the app") to see Maps working.

**Comment by rudsonramon** [comment]
I implemented the google places autocomplete, to search some address, but when I try to select one suggestion it is not working.  Do you know how to fix or make an workaround? https://stackoverflow.com/questions/65031936/expo-google-places-autocomplete-listview-not-clicable

**Comment by rudsonramon** [comment]
Thanks a lot for the help, it is fixed.
