### ISSUE TITLE
Google autocomplete - could not chose an item from the suggested list

### ISSUE THREAD

**Issue by rudsonramon** [calebnance/expo-uber#13]
I implemented the google places autocomplete, to search some address, but when I try to select one suggestion it is not working. Do you know how to fix or make an workaround? https://stackoverflow.com/questions/65031936/expo-google-places-autocomplete-listview-not-clicable

**Comment by calebnance** [comment]
hey i see this has now been fixed on your stackoverflow, going to close this. cheers!
